version: '3'
services:
  ues-auth-svc:
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
    - .:/go/src/github.com/tobyjsullivan/ues-auth-svc
    ports:
    - "3000:3000"
    depends_on:
    - "event-log-reader"
    environment:
    - SERVICE_LOG_ID=fbd8aab2-06ad-4738-84d8-1156adae860e
    - LOG_READER_API=http://event-log-reader:3000/
  ues-command-api:
    image: tobyjsullivan/ues-command-api:latest
    ports:
    - "3001:3000"
    depends_on:
    - "event-log"
    environment:
    - SERVICE_LOG_ID=fbd8aab2-06ad-4738-84d8-1156adae860e
    - LOG_WRITER_API=http://event-log:3000/
  event-log-reader:
    image: tobyjsullivan/event-log-reader:latest
    ports:
    - "3003:3000"
    depends_on:
    - "log-db"
    - "event-reader"
    environment:
    - EVENT_READER_API=http://event-reader:3000/
    - PG_HOSTNAME=log-db
    - PG_USERNAME=postgres
    - PG_PASSWORD=pass1234
    - PG_DATABASE=postgres
  event-log:
    image: tobyjsullivan/event-log:latest
    ports:
    - "3002:3000"
    depends_on:
    - "log-db"
    - "event-store"
    environment:
    - EVENT_STORE_API=http://event-store:3000/
    - PG_HOSTNAME=log-db
    - PG_USERNAME=postgres
    - PG_PASSWORD=pass1234
    - PG_DATABASE=postgres
  log-db:
    image: tobyjsullivan/logs-db:latest
    environment:
    - POSTGRES_PASSWORD=pass1234
    volumes:
    - ./data/log-db:/var/lib/postgresql/data
  event-reader:
    image: tobyjsullivan/event-reader.v3
    env_file:
    - ./env/event-reader.env
  event-store:
    image: tobyjsullivan/event-store.v3
    env_file:
    - ./env/event-store.env

