FROM golang

RUN ["go", "get", "github.com/codegangsta/gin"]

VOLUME ["/go/src/github.com/tobyjsullivan/ues-auth-svc"]

WORKDIR /go/src/github.com/tobyjsullivan/ues-auth-svc

EXPOSE 3000

CMD ["gin"]

